version: "3.3"
services: 
    # podinfo:
    #     image: "stefanprodan/podinfo"
    #     ports: 
    #         - "8082:9898"
    api:
        build: "api-gateway"
        environment: 
            PORT: "3000"
            TIMEOUT: "5000"
            URL_BOOK_SERVICE: "http://book:8080"
            URL_ORDER_SERVICE: "http://order:8081"
        ports: 
            - "80:3000"
        depends_on: 
            - book
            - order
    order:
        build: "order-service"
        # image: "ariefnhidayah/order-service:1.0"
        environment: 
            POSTGRES_HOST: "postgres"
            POSTGRES_DB: "orders"
            POSTGRES_USER: "docker"
            POSTGRES_PASSWORD: "docker"
            BOOK_SERVICE_HOST: "book:8080"
        # ports: 
        #     - "8081:8081"
        depends_on: 
            - postgres
            - book
    book:
        build: "book-service"
        environment: 
            POSTGRES_HOST: "postgres"
            POSTGRES_DB: "books"
            POSTGRES_USER: "docker"
            POSTGRES_PASSWORD: "docker"
        # ports: 
        #     - "8080:8080"
        depends_on: 
            - postgres
    postgres:
        image: "postgres:13-alpine"
        environment: 
            POSTGRES_DB: "books"
            POSTGRES_USER: "docker"
            POSTGRES_PASSWORD: "docker"
        expose: 
            - "5432"
        ports: 
            - "5432:5432"
        restart: "always"